import { StyleSheet } from 'react-native';

const palette = {
  ink: '#102033',
  inkSoft: '#395064',
  paper: '#f6f4ec',
  paperStrong: '#fffdf8',
  line: '#d7d8cd',
  lineSoft: '#e8e7dd',
  navy: '#17324d',
  navyAlt: '#244866',
  teal: '#0f766e',
  tealSoft: '#dbf3ef',
  amber: '#d97706',
  amberSoft: '#fdf0d5',
  rose: '#be123c',
  roseSoft: '#ffe4ea',
  ok: '#1f7a4f',
  okSoft: '#def7e8',
};

export const signatureWebStyle = `
  .m-signature-pad { box-shadow: none; border: 0; }
  .m-signature-pad--body { border: 1px solid #d7d8cd; border-radius: 18px; }
  .m-signature-pad--footer { display: none; }
  body, html { background: #fffdf8; }
`;

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: palette.paper,
  },
  backgroundCanvas: {
    ...StyleSheet.absoluteFill,
    overflow: 'hidden',
  },
  bgOrbOne: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 999,
    backgroundColor: '#d5efe9',
    top: -64,
    right: -92,
    opacity: 0.95,
  },
  bgOrbTwo: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: '#fbe5b8',
    top: 142,
    left: -110,
    opacity: 0.9,
  },
  bgOrbThree: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: '#e8edf4',
    bottom: -120,
    right: -68,
    opacity: 0.95,
  },
  bgMesh: {
    position: 'absolute',
    top: 94,
    right: 20,
    width: 140,
    height: 140,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(23, 50, 77, 0.08)',
    transform: [{ rotate: '14deg' }],
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.paper,
    gap: 12,
  },
  muted: {
    color: palette.inkSoft,
  },
  loginPage: {
    flex: 1,
    backgroundColor: '#efece2',
  },
  loginWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 28,
  },
  loginCard: {
    backgroundColor: 'rgba(255, 253, 248, 0.92)',
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(23, 50, 77, 0.08)',
    shadowColor: '#102033',
    shadowOpacity: 0.16,
    shadowRadius: 26,
    elevation: 10,
    gap: 10,
  },
  brand: {
    color: palette.navy,
    fontWeight: '900',
    fontSize: 14,
    letterSpacing: 2.4,
    textTransform: 'uppercase',
  },
  loginTitle: {
    color: palette.ink,
    fontSize: 31,
    lineHeight: 34,
    fontWeight: '900',
  },
  loginText: {
    color: palette.inkSoft,
    marginBottom: 6,
    lineHeight: 22,
  },
  loginBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  loginBadge: {
    backgroundColor: palette.tealSoft,
    borderColor: 'rgba(15, 118, 110, 0.14)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  loginBadgeText: {
    color: palette.teal,
    fontWeight: '800',
    fontSize: 12,
  },
  topbar: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 4,
  },
  topbarCard: {
    backgroundColor: palette.navy,
    borderRadius: 26,
    paddingHorizontal: 18,
    paddingVertical: 16,
    shadowColor: '#102033',
    shadowOpacity: 0.18,
    shadowRadius: 22,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  topbarMeta: {
    flex: 1,
    gap: 4,
  },
  topBrand: {
    color: '#e9f7f5',
    fontWeight: '900',
    fontSize: 11,
    letterSpacing: 2.1,
    textTransform: 'uppercase',
  },
  topTitle: {
    color: '#fffdf8',
    fontSize: 22,
    fontWeight: '900',
  },
  topUser: {
    color: '#c6d4df',
    fontSize: 13,
  },
  topPill: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  topPillText: {
    color: '#fef3c7',
    fontSize: 12,
    fontWeight: '800',
  },
  screen: {
    flex: 1,
  },
  screenContent: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 116,
    gap: 14,
  },
  screenHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    gap: 10,
  },
  title: {
    fontSize: 24,
    color: palette.ink,
    fontWeight: '900',
  },
  sectionTitle: {
    fontSize: 17,
    color: palette.ink,
    fontWeight: '900',
    marginTop: 8,
    marginBottom: 6,
  },
  introCard: {
    backgroundColor: 'rgba(255, 253, 248, 0.92)',
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: 'rgba(23, 50, 77, 0.09)',
    shadowColor: '#102033',
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 3,
    gap: 12,
  },
  introEyebrow: {
    color: palette.amber,
    fontWeight: '900',
    fontSize: 11,
    letterSpacing: 2.4,
    textTransform: 'uppercase',
  },
  introTitle: {
    color: palette.ink,
    fontWeight: '900',
    fontSize: 28,
    lineHeight: 31,
  },
  introText: {
    color: palette.inkSoft,
    lineHeight: 21,
  },
  introMetricsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  introMetricCard: {
    minWidth: 100,
    backgroundColor: '#f2f0e7',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: 'rgba(23, 50, 77, 0.06)',
    gap: 4,
  },
  introMetricAccent: {
    backgroundColor: palette.tealSoft,
    borderColor: 'rgba(15, 118, 110, 0.12)',
  },
  introMetricWarning: {
    backgroundColor: palette.amberSoft,
    borderColor: 'rgba(217, 119, 6, 0.12)',
  },
  introMetricValue: {
    color: palette.ink,
    fontSize: 22,
    fontWeight: '900',
  },
  introMetricLabel: {
    color: palette.inkSoft,
    fontSize: 12,
    fontWeight: '700',
  },
  panel: {
    backgroundColor: 'rgba(255, 253, 248, 0.96)',
    borderRadius: 26,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(23, 50, 77, 0.09)',
    shadowColor: '#102033',
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 2,
    gap: 10,
  },
  panelHeader: {
    gap: 4,
  },
  panelTitle: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: '900',
  },
  panelText: {
    color: palette.inkSoft,
    lineHeight: 20,
  },
  field: {
    marginBottom: 12,
  },
  label: {
    color: palette.inkSoft,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 7,
  },
  input: {
    backgroundColor: '#fbfaf5',
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    color: palette.ink,
    fontSize: 15,
  },
  textarea: {
    minHeight: 110,
    textAlignVertical: 'top',
  },
  textareaSmall: {
    minHeight: 76,
    textAlignVertical: 'top',
    marginTop: 8,
  },
  primaryBtn: {
    backgroundColor: palette.navy,
    borderRadius: 18,
    paddingVertical: 15,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#102033',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 3,
  },
  primaryText: {
    color: '#fffdf8',
    fontWeight: '900',
    fontSize: 14,
    letterSpacing: 0.4,
  },
  ghostBtn: {
    backgroundColor: 'rgba(255,253,248,0.92)',
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostBtnInverted: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.18)',
  },
  ghostText: {
    color: palette.navy,
    fontWeight: '900',
    fontSize: 13,
  },
  ghostTextInverted: {
    color: '#fffdf8',
  },
  dangerBtn: {
    backgroundColor: palette.roseSoft,
    borderColor: '#ffc6d4',
  },
  dangerText: {
    color: palette.rose,
  },
  disabled: {
    opacity: 0.45,
  },
  message: {
    marginHorizontal: 14,
    marginTop: 10,
    padding: 12,
    borderRadius: 18,
    fontWeight: '700',
  },
  messageErro: {
    color: '#8c1d3f',
    backgroundColor: palette.roseSoft,
    borderWidth: 1,
    borderColor: '#ffc6d4',
  },
  messageOk: {
    color: palette.ok,
    backgroundColor: palette.okSoft,
    borderWidth: 1,
    borderColor: '#b3ebc9',
  },
  messageAviso: {
    color: '#8d5d07',
    backgroundColor: palette.amberSoft,
    borderWidth: 1,
    borderColor: '#f5d695',
  },
  statusTabs: {
    gap: 8,
    paddingBottom: 4,
  },
  optionRow: {
    gap: 8,
    paddingBottom: 4,
  },
  optionWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    borderWidth: 1,
    borderColor: '#d4d2c4',
    backgroundColor: '#f7f5ee',
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  chipActive: {
    backgroundColor: palette.navy,
    borderColor: palette.navy,
  },
  chipDanger: {
    borderColor: '#ffc6d4',
    backgroundColor: palette.roseSoft,
  },
  chipText: {
    color: palette.inkSoft,
    fontWeight: '900',
    fontSize: 12,
  },
  chipTextActive: {
    color: '#fffdf8',
  },
  chipDangerText: {
    color: palette.rose,
  },
  osCard: {
    backgroundColor: 'rgba(255, 253, 248, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(23, 50, 77, 0.09)',
    borderRadius: 24,
    padding: 16,
    marginBottom: 10,
    shadowColor: '#102033',
    shadowOpacity: 0.07,
    shadowRadius: 18,
    elevation: 2,
    gap: 10,
  },
  osCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  osCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  osCardMetaPill: {
    backgroundColor: '#f1efe6',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignSelf: 'flex-start',
  },
  osCardMetaPillText: {
    color: palette.inkSoft,
    fontSize: 12,
    fontWeight: '700',
  },
  osCodigo: {
    color: palette.ink,
    fontWeight: '900',
    fontSize: 19,
  },
  statusBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 10,
    fontWeight: '900',
    fontSize: 11,
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.64)',
  },
  osTipo: {
    color: palette.inkSoft,
    fontWeight: '800',
  },
  osLocal: {
    color: palette.ink,
    fontSize: 15,
    lineHeight: 20,
  },
  osMeta: {
    color: palette.inkSoft,
    fontSize: 12,
    lineHeight: 17,
  },
  empty: {
    color: palette.inkSoft,
    textAlign: 'center',
    padding: 20,
  },
  emptyInline: {
    color: palette.inkSoft,
    paddingVertical: 8,
  },
  emptyCard: {
    backgroundColor: '#f3f1e8',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: palette.lineSoft,
    padding: 18,
    alignItems: 'center',
    gap: 6,
  },
  emptyTitle: {
    color: palette.ink,
    fontWeight: '900',
    fontSize: 16,
  },
  emptyText: {
    color: palette.inkSoft,
    textAlign: 'center',
    lineHeight: 20,
  },
  bottomTabs: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    backgroundColor: palette.navy,
    borderRadius: 24,
    padding: 6,
    borderWidth: 1,
    borderColor: 'rgba(23, 50, 77, 0.12)',
    flexDirection: 'row',
    shadowColor: '#102033',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 9,
  },
  bottomTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 13,
    borderRadius: 18,
  },
  bottomTabOn: {
    backgroundColor: '#fff8e7',
  },
  bottomText: {
    color: '#dbe7ef',
    fontWeight: '900',
  },
  bottomTextOn: {
    color: palette.navy,
  },
  detailCard: {
    backgroundColor: palette.navy,
    borderRadius: 28,
    padding: 18,
    marginTop: 4,
    gap: 8,
    shadowColor: '#102033',
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 4,
  },
  detailTitle: {
    fontSize: 27,
    color: '#fffdf8',
    fontWeight: '900',
    marginTop: 4,
  },
  detailMetaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 8,
  },
  detailMetaCard: {
    width: '47%',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    padding: 12,
    gap: 3,
  },
  detailMetaLabel: {
    color: '#cbd7df',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  detailMetaValue: {
    color: '#fffdf8',
    fontSize: 15,
    fontWeight: '800',
  },
  stateGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stateBtn: {
    width: '48%',
    backgroundColor: '#f6f3eb',
    borderWidth: 1,
    borderColor: '#d8d5c9',
    borderRadius: 18,
    paddingVertical: 13,
    alignItems: 'center',
  },
  stateBtnOn: {
    backgroundColor: palette.navy,
    borderColor: palette.navy,
  },
  stateBtnDisabled: {
    backgroundColor: '#f3f2eb',
    opacity: 0.56,
  },
  stateText: {
    color: palette.inkSoft,
    fontWeight: '900',
    textAlign: 'center',
    fontSize: 12,
  },
  stateTextOn: {
    color: '#fffdf8',
  },
  checkModel: {
    borderTopWidth: 1,
    borderTopColor: palette.lineSoft,
    paddingTop: 12,
    marginTop: 4,
    gap: 8,
  },
  checkModelTitle: {
    color: palette.ink,
    fontWeight: '900',
    fontSize: 15,
    marginBottom: 2,
  },
  checkItem: {
    backgroundColor: '#f5f3eb',
    borderWidth: 1,
    borderColor: palette.lineSoft,
    borderRadius: 18,
    padding: 12,
    gap: 8,
  },
  checkLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  checkBox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#93a1af',
    textAlign: 'center',
    lineHeight: 24,
    color: '#fffdf8',
    fontWeight: '900',
    backgroundColor: '#fffdf8',
  },
  checkBoxOn: {
    backgroundColor: palette.teal,
    borderColor: palette.teal,
  },
  checkText: {
    flex: 1,
    color: palette.ink,
    fontWeight: '700',
    lineHeight: 18,
  },
  signatureCard: {
    borderTopWidth: 1,
    borderTopColor: palette.lineSoft,
    paddingTop: 12,
    marginTop: 4,
    gap: 8,
  },
  signatureCanvas: {
    height: 250,
    backgroundColor: '#fffdf8',
    borderRadius: 18,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: palette.line,
  },
  signatureActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
    alignItems: 'center',
  },
  imagePickerCard: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#a6c5bf',
    borderRadius: 20,
    padding: 14,
    backgroundColor: palette.tealSoft,
    marginTop: 4,
    gap: 8,
  },
  imageRow: {
    gap: 10,
    marginTop: 6,
  },
  imageTile: {
    backgroundColor: '#f7f4ed',
    borderWidth: 1,
    borderColor: palette.lineSoft,
    borderRadius: 20,
    overflow: 'hidden',
  },
  imageThumb: {
    width: '100%',
    height: 176,
    backgroundColor: '#e8e7dd',
  },
  imageInfo: {
    padding: 12,
    gap: 6,
  },
  imageTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  imageTag: {
    alignSelf: 'flex-start',
    backgroundColor: palette.amberSoft,
    color: palette.amber,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '800',
  },
  inlineActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
  },
  separator: {
    height: 1,
    backgroundColor: palette.lineSoft,
    marginVertical: 4,
  },
});
